config/routes.rb
Rails.application.routes.draw do
  resources :stocks do 
    resources :researches
    resources :fundamentals
  end
  
  resources :actions

  resources :pages do
    member do
      get 'accounts'
      get 'reports'
      get 'graphs'
    end
  end

  get "welcome/index"

  root 'welcome#index'

  

end

app/models/research.rb
class Research < ApplicationRecord
  belongs_to :stock
  
  attr_accessor :confidence
  
  after_initialize :initialize_members
  def initialize_members
    @confidence = Togabou::CONFIDENCE_NONE
    if self.comment != nil
      if self.comment.include?(Togabou::CONFIDENCE_HIGH)
        @confidence = Togabou::CONFIDENCE_HIGH
      elsif self.comment.include?(Togabou::CONFIDENCE_MEDIUM)
        @confidence = Togabou::CONFIDENCE_MEDIUM
      elsif self.comment.include?(Togabou::CONFIDENCE_BLAH)
        @confidence = Togabou::CONFIDENCE_BLAH
      elsif self.comment.include?(Togabou::CONFIDENCE_LOW)
        @confidence = Togabou::CONFIDENCE_LOW
      end  
    end
  end
end

app/controllers/researches_controller.rb
class ResearchesController < ApplicationController
  def new
  end

  def create
    date = Date.civil(params[:research]["date(1i)"].to_i, params[:research]["date(2i)"].to_i, params[:research]["date(3i)"].to_i)
    eps_yr1_date = Date.civil(params[:research]["eps_yr1_date(1i)"].to_i, params[:research]["eps_yr1_date(2i)"].to_i, params[:research]["eps_yr1_date(3i)"].to_i)
    eps_yr2_date = Date.civil(params[:research]["eps_yr2_date(1i)"].to_i, params[:research]["eps_yr2_date(2i)"].to_i, params[:research]["eps_yr2_date(3i)"].to_i)

    @stock = Stock.find(params[:stock_id])
    @research = @stock.researches.new( :symbol => @stock.symbol,
					:date => date, 
					:eps => @stock.eps, 
					:div => @stock.div, 
					:growth => @stock.growth, 
					:pe_terminal => @stock.pe_terminal, 
					:payout => @stock.payout, 
					:book => @stock.book, 
					:roe => @stock.roe, 
					:price => @stock.price, 
					:div_plus_growth => @stock.div_plus_growth, 
					:eps_yield => @stock.eps_yield, 
					:div_yield => @stock.div_yield, 
					:five_year_cagr => @stock.five_year_cagr, 
					:ten_year_cagr => @stock.ten_year_cagr, 
					:five_year_croe => @stock.five_year_croe, 
					:ten_year_croe => @stock.ten_year_croe, 
					:eps_yr1_date => eps_yr1_date, 
					:eps_yr1 => params[:research][:eps_yr1],
					:eps_yr2_date => eps_yr2_date, 
					:eps_yr2 => params[:research][:eps_yr2],
					:comment => params[:research][:comment], 
					:stock_id => params[:stock_id]
					)

    @research.save
    redirect_to @stock
  end

  def edit
    @research = Research.find(params[:id])
  end

  def update
    @research = Research.find(params[:id])
    @stock = @research.stock
    
    if @research.update(params[:research].permit(:date, :eps_yr1_date, :eps_yr1, :eps_yr2_date, :eps_yr2, :comment ) )
      redirect_to @stock
    else
      render 'edit'
    end
  end

  def destroy
    @research = Research.find(params[:id])
    @stock = @research.stock
    @research.destroy
    redirect_to @stock
  end

  def show
    @research = Research.find(params[:id])
  end

  def index
    @researches = Research.all
  end

  private
    def research_params
      params.require(:research).permit(:symbol, :comment)
    end
end

app/helpers/researches_helper.rb
module ResearchesHelper
end

app/views/researches/_research.html.erb
<% if research.growth != nil %>
<h2><%= research.date %></h2>
<table>
<tr>
    <th>EPS</th>
    <th>Div</th>
    <th>Growth</th>
    <th>PE Ter</th>
    <th>Payout</th>
    <th>Book</th>
    <th>ROE</th>
    <th>Price</th>
    <th>Div+Growth</th>
    <th>EYield</th>
    <th>DYield</th>
    <th>5 CAGR</th>
    <th>10 CAGR</th>
    <th>5 CROE</th>
    <th>10 CROE</th>
  </tr>
  <tr>
    <td class="number"><%= number_with_precision( research.eps, :precision => 2, :delimiter => ",") %></td>
    <td class="number"><%= number_with_precision( research.div, :precision => 2, :delimiter => ",") %></td>
    <td class="number"><%= research.growth * 100 %>%</td>
    <td class="number"><%= research.pe_terminal %></td>
    <td class="number"><%= research.payout * 100 %>%</td>
    <td class="number"><%= number_with_precision( research.book, :precision => 2, :delimiter => ",") %></td>
    <td class="number"><%= research.roe * 100 %>%</td>
    <td class="number"><%= number_with_precision( research.price, :precision => 2, :delimiter => ",") %></td>
    <td class="number"><%= number_with_precision( research.div_plus_growth * 100, :precision => 2, :delimiter => ",") %>%</td>
    <td class="number"><%= number_with_precision( research.eps_yield * 100, :precision => 2, :delimiter => ",") %>%</td>
    <td class="number"><%= number_with_precision( research.div_yield * 100, :precision => 2, :delimiter => ",") %>%</td>
    <td class="number"><%= number_with_precision( research.five_year_cagr * 100, :precision => 2, :delimiter => ",") %>%</td>
    <td class="number"><%= number_with_precision( research.ten_year_cagr * 100, :precision => 2, :delimiter => ",") %>%</td>
    <td class="number"><%= number_with_precision( research.five_year_croe * 100, :precision => 2, :delimiter => ",") %>%</td>
    <td class="number"><%= number_with_precision( research.ten_year_croe * 100, :precision => 2, :delimiter => ",") %>%</td>
  </tr>
</table>  

<table style="width: 100%;">
  <tr>
    <td>
      <table>
        <tr><td><%= research.eps_yr2_date %></td><td><%= research.eps_yr2 %></td><td/></tr>
        <tr><td><%= research.eps_yr1_date %></td><td><%= research.eps_yr1 %></td><td/></tr>
      </table>
    </td>
    <td style="word-wrap: break-word"><pre><div style="word-wrap: break-word;"><%= research.comment %></div></pre></td>
  </tr>
</table>

<%= link_to 'Edit', edit_stock_research_path(@stock, research) %> | <%= link_to 'Delete', stock_research_path(@stock, research), :confirm => 'Are you sure?', :method => :delete %>
<% end %>

app/views/researches/edit.html.erb
<h1>Edit Research</h1>
<%= @research.date %>
<%= form_for [:stock, @research], url: stock_research_path(:id, @research.id), method: :patch do |f| %>
<table>
<tr><td>
<table>
<tr><td><%= f.date_select :date %></td><td/></tr>
<tr><td><%= f.date_select :eps_yr2_date %></td>
<td><%= f.text_field :eps_yr2 %></td></tr>
<tr><td><%= f.date_select :eps_yr1_date %></td>
<td><%= f.text_field :eps_yr1 %></td</tr>
</table>
</td><td>
    <%= f.text_area :comment, :cols => "80", :rows => "10" %>
</td></tr>
</table>

  <%= f.submit %>
<% end %>

app/views/researches/index.html.erb
<h1>Listing researches</h1>
 
<table>
  <tr>
    <th>Symbol</th>
    <th>Comment</th>
  </tr>
 
  <% @researches.each do |research| %>
    <tr>
      <td><%= research.symbol %></td>
      <td><%= research.comment %></td>
    </tr>
  <% end %>
</table>

app/views/researches/new.html.erb
<h1>New Research</h1>

<%= form_for :research, url: researches_path do |f| %>
  <p>
    <%= f.label :symbol %><br>
    <%= f.text_field :symbol %>
  </p>
 
  <p>
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/researches/show.html.erb
<h1>Show Research</h1>