config/routes.rb
Rails.application.routes.draw do
  resources :stocks do 
    resources :researches
    resources :fundamentals
  end
  
  resources :actions

  resources :pages do
    member do
      get 'accounts'
      get 'reports'
      get 'graphs'
    end
  end

  get "welcome/index"

  root 'welcome#index'

  

end

app/models/actions_type.rb
class ActionsType < ApplicationRecord
end

app/controllers/actions_controller.rb
class ActionsController < ApplicationController
  attr_accessor :actions_types_all

  def initialize
    @actions_types_all = ActionsType.all
    super
  end

  def new
    @action = Action.new
  end

  def create
    @action = Action.new(action_params)
    @action.execute
    redirect_to actions_path
  end

  def destroy
    @action = Action.find(params[:id])
    @action.undo

    redirect_to actions_path
  end

  def show
    @action = Action.find(params[:id])
  end

  def index
    @actions = Action.all
    @actions = @actions.sort { |a,b| b.created_at <=> a.created_at }
  end

  private
    def action_params
      params.require(:foo).permit(:date, :actions_type_id, :description, :value1, :value2, :value3, :value4, :value5, :symbol)
    end

end

app/helpers/actions_helper.rb
module ActionsHelper
end

app/views/actions/index.html.erb
<h1>Actions</h1>
<style type="text/css">
table {
  border-spacing: 20px 0;
}
td.heading {
    text-align: center;
    font-weight: bold;
}
td.number {
    text-align: right;
}
td.symbol {
    font-weight: bold;
}
</style>
<%= link_to 'New', new_action_path %> | <%= link_to 'Rollback', action_path( @actions.first ), :confirm => 'Are you sure?', :method => :delete %>
<table>
  <tr>
    <th>Date</th>
    <th>Description</th>
    <th>Amount</th>
    <th>Symbol</th>
    <th>Created At</th>
  </tr>
  <% @actions.each do |action| %>
    <tr>
      <td><%= action.date %></td>
      <td><%= action.actions_type.description if !action.actions_type.nil? %></td>
      <td class="number"><%= number_with_precision( action.value1, :precision => 2, :delimiter => ",") %></td>
      <td><%= action.symbol.to_s %></td>
      <td><%= action.created_at.to_s %></td>
    </tr>
  <% end %>
</table>

app/views/actions/new.html.erb
<h1>Create Action</h1>

<%
	actions_type_id = 3
	if params[:actions_type_id] != nil
	  actions_type_id = params[:actions_type_id].to_i
	end
%>

<form method="GET">
  <label for="actions_type_id">Actions Type:</label>
  <select name="actions_type_id">
  <% @actions_types_all.sort { |a,b| a.description <=> b.description }.each do |actions_type| %>
    <% if actions_type.id == actions_type_id %>
      <option value="<%= actions_type.id %>" selected="selected"><%= actions_type.description %></option>
    <% else %>
      <option value="<%= actions_type.id %>"><%= actions_type.description %></option>
    <% end %>
  <% end %>
  </select>
  <input type="submit" />
</form>

<% cur_actions_type = ActionsType.find( actions_type_id ) %>
<h2><%= cur_actions_type.description %></h2>
<%= form_for @action, as: :foo, url: actions_path do |f| %>
  <%= f.hidden_field :actions_type_id, :value => actions_type_id %>

  <p>
    <%= f.label Date.today %><br>
    <%= f.date_select :date, :default => Date.today %>
  </p>

  <% unless cur_actions_type.symbol.nil? %>
  <p>
    <%= f.label :symbol %><br>
    <%= f.text_field :symbol %>
  </p>
  <% end %>

  <% unless cur_actions_type.value1.nil? %>
  <p>
    <%= f.label :value1, cur_actions_type.value1 %><br>
    <%= f.number_field :value1, step: :any %>
  </p>
  <% end %>

  <% unless cur_actions_type.value2.nil? %>
  <p>
    <%= f.label :value2, cur_actions_type.value2 %><br>
    <%= f.number_field :value2, step: :any %>
  </p>
  <% end %>

  <% unless cur_actions_type.value3.nil? %>
  <p>
    <%= f.label :value3, cur_actions_type.value3 %><br>
    <%= f.number_field :value3, step: :any %>
  </p>
  <% end %>

  <% unless cur_actions_type.value4.nil? %>
  <p>
    <%= f.label :value4, cur_actions_type.value4 %><br>
    <%= f.number_field :value4, step: :any %>
  </p>
  <% end %>

  <% unless cur_actions_type.value5.nil? %>
  <p>
    <%= f.label :value5, cur_actions_type.value5 %><br>
    <%= f.number_field :value5, step: :any %>
  </p>
  <% end %>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/actions/show.html.erb
<p>
  <strong>Date:</strong>
  <%= @action.date %>
</p>
 
<p>
  <strong>Description:</strong>
  <%= @action.description %>
</p>