config/routes.rb
Rails.application.routes.draw do
  resources :stocks do 
    resources :researches
    resources :fundamentals
  end
  
  resources :actions

  resources :pages do
    member do
      get 'accounts'
      get 'reports'
      get 'graphs'
    end
  end

  get "welcome/index"

  root 'welcome#index'

  

end

app/models/stock.rb
require 'open-uri'

def get_scalar( conn, sql )
  res = conn.execute( sql )
  if res == nil or res.first == nil
    0
  else
    res.first['value']
  end
end

class Stock < ApplicationRecord
  has_many :researches, -> { order "date DESC" }
  has_many :fundamentals, -> { order "date DESC" }
  has_many :constituents, -> { order "portfolio_id ASC" }
  accepts_nested_attributes_for :constituents, update_only: true

  attr_accessor :pe
  attr_accessor :eps_yield
  attr_accessor :div_yield
  attr_accessor :div_plus_growth
  attr_accessor :five_year_cagr
  attr_accessor :ten_year_cagr
  attr_accessor :five_year_croe
  attr_accessor :ten_year_croe
  attr_accessor :confidence
  attr_accessor :confidence_num

  after_initialize :initialize_members
  def initialize_members
    if ( ( self.price == nil || self.price <= 0 ) && self.symbol != nil )
      # Populate price from AlphaVantage
      logger.info sprintf( "Retrieving last from AlphaVantage for %s...", self.symbol )
      url = sprintf("https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol=%s&apikey=2YG6SAN57NRYNPJ8", self.symbol)
      data = JSON.load(URI.open(url))
      self.price = data['Global Quote']['05. price'].to_f
      logger.info sprintf( "Retrieved %f from AlphaVantage for %s", self.price, self.symbol )
    end

    # Populate calculated values
    if self.price != nil && self.price > 0
      @pe = self.price / self.eps
      @eps_yield = self.eps / self.price
      @div_yield = self.div / self.price
      @div_plus_growth = self.div_yield + self.growth
      @five_year_cagr = cagr( 5 )
      @ten_year_cagr = cagr( 10 )
      @five_year_croe = croe( 5 )
      @ten_year_croe = croe( 10 )
    end
    
    @confidence = Togabou::CONFIDENCE_NONE
    if self.researches.length > 0
      @confidence = self.researches[0].confidence
    end

    if self.confidence == Togabou::CONFIDENCE_HIGH
        @confidence_num = 0
    elsif self.confidence == Togabou::CONFIDENCE_MEDIUM
        @confidence_num = 1
    elsif self.confidence == Togabou::CONFIDENCE_NONE
        @confidence_num = 2
    elsif self.confidence == Togabou::CONFIDENCE_BLAH
        @confidence_num = 3
    elsif self.confidence == Togabou::CONFIDENCE_LOW
        @confidence_num = 4
    end
  end

  def cagr( years )
    div_bucket = 0.0
    eps = self.eps
    (1..years).each do |i|
      div_bucket = div_bucket * (1 + Togabou::DIV_GROWTH)
      div_bucket = div_bucket + (eps * self.payout)
      eps = eps * (1 + self.growth)
    end
    ((((eps * self.pe_terminal) + div_bucket) / self.price) ** (1.0 / years)) - 1
  end

  def croe( years )
    div_bucket = 0.0
    eps = 0
    book = self.book
    div = 0
    (1..years).each do |i|
      div_bucket = div_bucket * (1 + Togabou::DIV_GROWTH)
      eps = book * self.roe
      div = eps * self.payout
      div_bucket = div_bucket + div
      book = book + eps - div
    end
    ((((eps * self.pe_terminal) + div_bucket) / self.price) ** (1.0 / years)) - 1
  end

  def reminder
    ret = 0
    if self.researches.length <= 0
      ret = 2
    elsif self.researches[ 0 ].date > 1.month.ago
      ret = 0
    elsif self.researches[ 0 ].date > 3.months.ago
      ret = 1
    else
      ret = 2
    end
    ret
  end

  def two_year_eps
    ret = 0
    if self.researches.length <= 0 or self.fundamentals.length <= 0 or self.researches[0].eps_yr2.nil? or self.fundamentals[0].eps.nil? or self.fundamentals[0].eps <= 0
      ret = 0
    else
      ret = ( self.researches[0].eps_yr2 / self.fundamentals[0].eps ) ** 0.5 - 1
    end
    ret
  end

  def seven_year_eps
    ret = 0
    if self.researches.length <= 0 or self.fundamentals.length <= 5 or self.researches[0].eps_yr2.nil? or self.fundamentals[5].eps.nil? or self.fundamentals[5].eps <= 0
      ret = 0
    else
      ret = ( self.researches[0].eps_yr2 / self.fundamentals[ 5 ].eps ) ** ( 1 / 7.0 ) - 1
    end
    ret
  end

  def x_year_eps( year )
    ret = 0
    if self.fundamentals.length <= year || self.fundamentals[ year ].eps <= 0
      ret = 0
    else
      ret = ( self.fundamentals[0].eps / self.fundamentals[ year ].eps ) ** ( 1.0 / year ) - 1
    end
    ret
  end

  def average_roe( year )
    ret = 0
    if self.fundamentals.length < year
      ret = 0
    else
      ret = self.fundamentals[0, year].inject(0.0){ |sum,e| sum += e.roe } / year
    end
    ret
  end

  def average_pe_high( year )
    ret = 0
    if self.fundamentals.length < year
      ret = 0
    else
      sorted = self.fundamentals[0, year].sort {|a,b| a.pe_high <=> b.pe_high }
      ret = year % 2 == 1 ? sorted[year/2.0].pe_high : (sorted[year/2.0 - 1].pe_high + sorted[year/2.0]).pe_high / 2.0
    end
    ret
  end

  def average_pe_low( year )
    ret = 0
    if self.fundamentals.length < year
      ret = 0
    else
      sorted = self.fundamentals[0, year].sort {|a,b| a.pe_low <=> b.pe_low }
      ret = year % 2 == 1 ? sorted[year/2.0].pe_low : (sorted[year/2.0 - 1].pe_low + sorted[year/2.0]).pe_low / 2.0
    end
    ret
  end
end

app/controllers/stocks_controller.rb
require 'assets.rb'

class StocksController < ApplicationController
  attr_accessor :assets

  def initialize
    @assets = Assets.new
    super
  end

  def portfolio_constituents( portfolio_id )
    ret = Constituent.where( sprintf( "portfolio_id = %d and model > 0", portfolio_id ) )
    ret.sort { |a,b| [ b.value.to_f ] <=> [ a.value.to_f ] }
  end

  def portfolio_stocks( portfolio_id )
    portfolio_constituents( portfolio_id ).map!{ |constituent| constituent.stock }
  end

  def watch_stocks( portfolio_id )
    ret = Stock.where("model >= 0 and hidden = false") - portfolio_stocks( portfolio_id )
    ret.sort { |a,b| [ a.confidence_num, b.five_year_cagr.to_f ] <=> [ b.confidence_num, a.five_year_cagr.to_f ] }
  end

  def monitor_stocks
    ret = Stock.where( "model < 0" )
    ret.sort { |a,b| [ a.id.to_f ] <=> [ b.id.to_f ] }
  end

  def new
    @stock = Stock.new
    @stock.constituents.build
  end

  def create
    #@stock = Stock.new(params[:stock].permit(:symbol, :eps, :div, :growth, :pe_terminal, :payout, :book, :roe, constituents_attributes: [:model, :id, :stock_id]))
    @stock = Stock.new(params[:stock].permit!)
    #constituent = @stock.constituents.build
    @stock.save
    redirect_to @stock
  end

  def index
    @stocks = Stock.all
  end

  def show
    @stock = Stock.find(params[:id])
  end

  def edit
    @stock = Stock.find(params[:id])
  end

  def update
    @stock = Stock.find(params[:id])
    #if @stock.update(params[:stock].permit(:eps, :div, :growth, :pe_terminal, :payout, :book, :roe, :price, constituents_attributes: [:model, :id, :stock_id] ) )
    if @stock.update( stock_params )
      redirect_to @stock
    else
      render 'edit'
    end
  end

  def portfolio_total( portfolio_id )
    self.assets.portfolio_internal( portfolio_id ).total
  end

  def portfolio_total_percent( portfolio_id )
    self.assets.portfolio_internal( portfolio_id ).total.to_f / self.assets.rotc_total.to_f
  end

  def portfolio_cash( portfolio_id )
    self.assets.portfolio_internal( portfolio_id ).cash
  end

  def portfolio_cash_percent( portfolio_id )
    self.assets.portfolio_internal( portfolio_id ).cash.to_f / self.assets.portfolio_internal( portfolio_id ).total.to_f
  end

  def portfolio_check( portfolio_id )
    ( self.portfolio_constituents( portfolio_id ).inject(0.0){ |sum,x| sum + x.value.to_f } + portfolio_cash( portfolio_id ).to_f ) / portfolio_total( portfolio_id ).to_f
  end

  def portfolio_model_check( portfolio_id )
    self.portfolio_constituents( portfolio_id ).inject(0.0){ |sum,x| sum + x.model.to_f }
  end

  def portfolio_eps_wtd_total( portfolio_id )
    self.portfolio_constituents( portfolio_id ).inject(0.0){ |sum,x| sum + x.eps_yield_wtd.to_f }
  end

  def portfolio_div_wtd_total( portfolio_id )
    self.portfolio_constituents( portfolio_id ).inject(0.0){ |sum,x| sum + x.div_yield_wtd.to_f }
  end

  def portfolio_cagr5yr_wtd_total( portfolio_id )
    self.portfolio_constituents( portfolio_id ).inject(0.0){ |sum,x| sum + x.cagr5yr_wtd.to_f }
  end

  def portfolio_cagr10yr_wtd_total( portfolio_id )
    self.portfolio_constituents( portfolio_id ).inject(0.0){ |sum,x| sum + x.cagr10yr_wtd.to_f }
  end

  private
    def stock_params
      params.require(:stock).permit(:symbol, :eps, :div, :growth, :pe_terminal, :payout, :book, :roe, constituents_attributes: [:model, :id, :stock_id] )
      #params.require(:stock).permit!
    end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/_portfolio.html.erb
<table>
  <tr><td class="symbol">Total</td><td class="number"><%= number_with_precision( controller.portfolio_total( portfolio_id ), :precision => 2, :delimiter => "," ) %></td><td class="number"><%= number_with_precision( controller.portfolio_total_percent( portfolio_id ) * 100, :precision => 2, :delimiter => ",") %>%</td></tr>
  <tr>
    <th>Symbol</th>
    <th>EPS</th>
    <th>Div</th>
    <th>Growth</th>
    <th>PE Ter</th>
    <th>Payout</th>
    <th>Book</th>
    <th>ROE</th>
    <th>%Model</th>
    <th>Price</th>
    <th>Value</th>
    <th>%Portfolio</th>
    <th>%Off</th>
    <th>Div+Growth</th>
    <th>EYield</th>
    <th>DYield</th>
    <th>5 CAGR</th>
    <th>10 CAGR</th>
    <th>5 CROE</th>
    <th>10 CROE</th>
    <th>Confidence</th>
  </tr>

  <% controller.portfolio_constituents( portfolio_id ).each do |constituent|
       stock = constituent.stock
    %>
    <tr>
      <td class="<%= if stock.reminder == 0 then "symbol" elsif stock.reminder == 1 then "symbol_yellow" else "symbol_red" end %>"><%= link_to stock.symbol, stock_path(stock) %></td>
      <td class="number"><%= number_with_precision( stock.eps, :precision => 2, :delimiter => ",") %></td>
      <td class="number"><%= number_with_precision( stock.div, :precision => 2, :delimiter => ",") %></td>
      <td class="number"><%= stock.growth*100 %>%</td>
      <td class="number"><%= stock.pe_terminal %></td>
      <td class="number"><%= stock.payout * 100 %>%</td>
      <td class="number"><%= number_with_precision( stock.book, :precision => 2, :delimiter => ",") %></td>
      <td class="number"><%= stock.roe * 100 %>%</td>
      <td class="number"><%= constituent.model * 100 %>%</td>
      <td class="number"><%= number_with_precision( stock.price, :precision => 2, :delimiter => ",") %></td>
      <td class="number"><%= number_with_precision( constituent.value, :precision => 2, :delimiter => ",") %></td>
      <td class="number"><%= number_with_precision( constituent.actual * 100, :precision => 2, :delimiter => ",") %>%</td>
      <td class="number"><%= number_with_precision( constituent.off * 100, :precision => 2, :delimiter => ",") %>%</td>
      <td class="number"><%= number_with_precision( stock.div_plus_growth * 100, :precision => 2, :delimiter => ",") %>%</td>
      <td class="number"><%= number_with_precision( stock.eps_yield * 100, :precision => 2, :delimiter => ",") %>%</td>
      <td class="number"><%= number_with_precision( stock.div_yield * 100, :precision => 2, :delimiter => ",") %>%</td>
      <td class="number"><%= number_with_precision( stock.five_year_cagr * 100, :precision => 2, :delimiter => ",") %>%</td>
      <td class="number"><%= number_with_precision( stock.ten_year_cagr * 100, :precision => 2, :delimiter => ",") %>%</td>
      <td class="number"><%= number_with_precision( stock.five_year_croe * 100, :precision => 2, :delimiter => ",") %>%</td>
      <td class="number"><%= number_with_precision( stock.ten_year_croe * 100, :precision => 2, :delimiter => ",") %>%</td>
      <td class="<%= if stock.confidence == Togabou::CONFIDENCE_HIGH then "confidence_green" 
        elsif stock.confidence == Togabou::CONFIDENCE_MEDIUM then "confidence_yellow"
        elsif stock.confidence == Togabou::CONFIDENCE_BLAH then "confidence_gray"
        elsif stock.confidence == Togabou::CONFIDENCE_LOW then "confidence_red"
        end %>"><%= stock.confidence %></td>
    </tr>
  <% end %>
  <tr><td/><td/><td/><td/><td/><td/><td/><td/>
  	<td class="number"><%= number_with_precision( controller.portfolio_model_check( portfolio_id ) * 100, :precision => 1, :delimiter => ",") %>%</td>
  	<td class="symbol">CASH</td><td class="number"><%= number_with_precision( controller.portfolio_cash( portfolio_id ), :precision => 2, :delimiter => ",") %></td></td>
  	<td class="number"><%= number_with_precision( controller.portfolio_cash_percent( portfolio_id ) * 100, :precision => 2, :delimiter => ",") %>%</td><td/><td/>
  	<td class="number"><%= number_with_precision( controller.portfolio_eps_wtd_total( portfolio_id ) * 100, :precision => 2, :delimiter => ",") %>%</td>
  	<td class="number"><%= number_with_precision( controller.portfolio_div_wtd_total( portfolio_id ) * 100, :precision => 2, :delimiter => ",") %>%</td>
  	<td class="number"><%= number_with_precision( controller.portfolio_cagr5yr_wtd_total( portfolio_id ) * 100, :precision => 2, :delimiter => ",") %>%</td>
  	<td class="number"><%= number_with_precision( controller.portfolio_cagr10yr_wtd_total( portfolio_id ) * 100, :precision => 2, :delimiter => ",") %>%</td>
  <tr><td/><td/><td/><td/><td/><td/><td/><td/><td/><td/><td class="symbol">CHECK</td></td><td class="number"><%= number_with_precision( controller.portfolio_check( portfolio_id ) * 100, :precision => 2, :delimiter => ",") %>%</td>
  <tr><td>&nbsp</td></tr>
  <tr><td class="symbol"><%= link_to 'New', new_stock_path %></td></tr>
  <% controller.watch_stocks( portfolio_id ).each do |stock| %>
    <tr>
      <td class="<%= if stock.reminder == 0 then "symbol" elsif stock.reminder == 1 then "symbol_yellow" else "symbol_red" end %>"><%= link_to stock.symbol, stock_path(stock) %></td>
      <td class="number"><%= number_with_precision( stock.eps, :precision => 2, :delimiter => ",") %></td>
      <td class="number"><%= number_with_precision( stock.div, :precision => 2, :delimiter => ",") %></td>
      <td class="number"><%= stock.growth*100 %>%</td>
      <td class="number"><%= stock.pe_terminal %></td>
      <td class="number"><%= stock.payout * 100 %>%</td>
      <td class="number"><%= number_with_precision( stock.book, :precision => 2, :delimiter => ",") %></td>
      <td class="number"><%= stock.roe * 100 %>%</td>
      <td class="number"></td>
      <td class="number"><%= number_with_precision( stock.price, :precision => 2, :delimiter => ",") %></td>
      <td class="number"></td>
      <td class="number"></td>
      <td class="number"></td>
      <td class="number"><%= number_with_precision( stock.div_plus_growth * 100, :precision => 2, :delimiter => ",") %>%</td>
      <td class="number"><%= number_with_precision( stock.eps_yield * 100, :precision => 2, :delimiter => ",") %>%</td>
      <td class="number"><%= number_with_precision( stock.div_yield * 100, :precision => 2, :delimiter => ",") %>%</td>
      <td class="number"><%= number_with_precision( stock.five_year_cagr * 100, :precision => 2, :delimiter => ",") %>%</td>
      <td class="number"><%= number_with_precision( stock.ten_year_cagr * 100, :precision => 2, :delimiter => ",") %>%</td>
      <td class="number"><%= number_with_precision( stock.five_year_croe * 100, :precision => 2, :delimiter => ",") %>%</td>
      <td class="number"><%= number_with_precision( stock.ten_year_croe * 100, :precision => 2, :delimiter => ",") %>%</td>
      <td class="<%= if stock.confidence == Togabou::CONFIDENCE_HIGH then "confidence_green" 
        elsif stock.confidence == Togabou::CONFIDENCE_MEDIUM then "confidence_yellow"
        elsif stock.confidence == Togabou::CONFIDENCE_BLAH then "confidence_gray"
        elsif stock.confidence == Togabou::CONFIDENCE_LOW then "confidence_red"
        end %>"><%= stock.confidence %></td>
    </tr>
  <% end %>
</table>

app/views/stocks/new.html.erb
<h1>Create Stock</h1>

<%= form_for :stock, url: stocks_path do |f| %>
  <p>
    <%= f.label :symbol %><br>
    <%= f.text_field :symbol %>
  </p>
  <p>
    <%= f.label :eps %><br>
    <%= f.text_field :eps %>
  </p>
  <p>
    <%= f.label :div %><br>
    <%= f.text_field :div %>
  </p>
  <p>
    <%= f.label :growth %><br>
    <%= f.text_field :growth %>
  </p>
  <p>
    <%= f.label :pe_terminal %><br>
    <%= f.text_field :pe_terminal %>
  </p>
  <p>
    <%= f.label :payout %><br>
    <%= f.text_field :payout %>
  </p>
  <p>
    <%= f.label :book %><br>
    <%= f.text_field :book %>
  </p>
  <p>
    <%= f.label :roe %><br>
    <%= f.text_field :roe %>
  </p>
  <p>
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/stocks/show.html.erb
<h1><%= @stock.symbol %></h1>
<style type="text/css">
pre {
 white-space: pre-wrap;       /* css-3 */
 white-space: -moz-pre-wrap;  /* Mozilla, since 1999 */
 white-space: -pre-wrap;      /* Opera 4-6 */
 white-space: -o-pre-wrap;    /* Opera 7 */
 word-wrap: break-word;       /* Internet Explorer 5.5+ */
}
table {
  border-spacing: 20px 0;
}
td.number {
    text-align: right;
}
td.symbol {
    font-weight: bold;
}
</style>

<%= form_for :stock, url: stock_path(@stock.id), method: :patch do |f| %>
<table>
<tr>
    <th>EPS</th>
    <th>Div</th>
    <th>Growth</th>
    <th>PE Ter</th>
    <th>Payout</th>
    <th>Book</th>
    <th>ROE</th>
    <% @stock.constituents.each do |constituent| %>
      <th>%M<%= constituent.portfolio_id.to_s %></th>
    <% end %>
    <th>Price</th>
    <th>PE</th>
    <th>Div+Growth</th>
    <th>EYield</th>
    <th>DYield</th>
    <th>5 CAGR</th>
    <th>10 CAGR</th>
    <th>5 CROE</th>
    <th>10 CROE</th>
  </tr>
  <tr>
    <td class="number"><%= number_with_precision( @stock.eps, :precision => 2, :delimiter => ",") %></td>
    <td class="number"><%= number_with_precision( @stock.div, :precision => 2, :delimiter => ",") %></td>
    <td class="number"><%= @stock.growth*100 %>%</td>
    <td class="number"><%= @stock.pe_terminal %></td>
    <td class="number"><%= @stock.payout * 100 %>%</td>
    <td class="number"><%= number_with_precision( @stock.book, :precision => 2, :delimiter => ",") %></td>
    <td class="number"><%= @stock.roe * 100 %>%</td>
    <% @stock.constituents.each do |constituent| %>
      <td class="number"><%= number_with_precision( constituent.model * 100, :precision => 2, :delimiter => ",") %>%</td>
    <% end %>
    <td class="number"><%= number_with_precision( @stock.price, :precision => 2, :delimiter => ",") %></td>
    <td class="number"><%= number_with_precision( @stock.pe, :precision => 2, :delimiter => ",") %></td>
    <td class="number"><%= number_with_precision( @stock.div_plus_growth * 100, :precision => 2, :delimiter => ",") %>%</td>
    <td class="number"><%= number_with_precision( @stock.eps_yield * 100, :precision => 2, :delimiter => ",") %>%</td>
    <td class="number"><%= number_with_precision( @stock.div_yield * 100, :precision => 2, :delimiter => ",") %>%</td>
    <td class="number"><%= number_with_precision( @stock.five_year_cagr * 100, :precision => 2, :delimiter => ",") %>%</td>
    <td class="number"><%= number_with_precision( @stock.ten_year_cagr * 100, :precision => 2, :delimiter => ",") %>%</td>
    <td class="number"><%= number_with_precision( @stock.five_year_croe * 100, :precision => 2, :delimiter => ",") %>%</td>
    <td class="number"><%= number_with_precision( @stock.ten_year_croe * 100, :precision => 2, :delimiter => ",") %>%</td>
  </tr>
      <tr>
        <td> <%= f.text_field :eps, :value => @stock.eps, :size => 4 %></td>
        <td> <%= f.text_field :div, :value => @stock.div, :size => 4 %></td>
        <td> <%= f.text_field :growth, :value => @stock.growth, :size => 4 %></td>
        <td> <%= f.text_field :pe_terminal, :value => @stock.pe_terminal, :size => 4 %></td>
        <td> <%= f.text_field :payout, :value => @stock.payout, :size => 4 %></td>
        <td> <%= f.text_field :book, :value => @stock.book, :size => 4 %></td>
        <td> <%= f.text_field :roe, :value => @stock.roe, :size => 4 %></td>
        <% @stock.constituents.each do |constituent| %>
          <%= f.fields_for 'constituents_attributes[]', constituent, :hidden_field_id => true do |fc| %>
            <td>
              <%= fc.text_field :model, :value => constituent.model, :size => 4 %>
              <%= fc.hidden_field :id, :value => constituent.id %>
            </td>
          <% end %>
        <% end %>
      </tr>
    </table>
  <p><%= f.submit %></p>
<% end %>

<table>
<tr>
  <th>2 Yr EPS</th>
  <th>7 Yr EPS</th>
  <th>5 Yr EPS</th>
  <th>10 Yr EPS</th>
  <th>5 Yr ROE</th>
  <th>5 Yr PE High</th>
  <th>5 Yr PE Low</th>
</tr>
<tr>
  <td class="number"><%= number_with_precision( @stock.two_year_eps*100, :precision => 2, :delimiter => ",") %>%</td>
  <td class="number"><%= number_with_precision( @stock.seven_year_eps*100, :precision => 2, :delimiter => ",") %>%</td>
  <td class="number"><%= number_with_precision( @stock.x_year_eps(5)*100, :precision => 2, :delimiter => ",") %>%</td>
  <td class="number"><%= number_with_precision( @stock.x_year_eps(10)*100, :precision => 2, :delimiter => ",") %>%</td>
  <td class="number"><%= number_with_precision( @stock.average_roe(5)*100, :precision => 2, :delimiter => ",") %>%</td>
  <td class="number"><%= number_with_precision( @stock.average_pe_high(5), :precision => 2, :delimiter => ",") %></td>
  <td class="number"><%= number_with_precision( @stock.average_pe_low(5), :precision => 2, :delimiter => ",") %></td>
</tr>
<tr><td>&nbsp</td></tr>
</table>

<table>
<tr>
    <th>Date</th>
    <th>EPS</th>
    <th>Div</th>
    <th>PE</th>
    <th>PE High</th>
    <th>PE Low</th>
    <th>ROE</th>
    <th>ROA</th>
    <th>Market Cap</th>
    <th>Shares Out</th>
</tr>
<% @stock.fundamentals.each do |fundamental| %>
<tr>
  <td><%= fundamental.date %></td>
  <td class="number"><%= number_with_precision( fundamental.eps, :precision => 2, :delimiter => ",") %></td>
  <td class="number"><%= number_with_precision( fundamental.div, :precision => 2, :delimiter => ",") %></td>
  <td class="number"><%= number_with_precision( fundamental.pe, :precision => 0, :delimiter => ",") %></td>
  <td class="number"><%= number_with_precision( fundamental.pe_high, :precision => 0, :delimiter => ",") %></td>
  <td class="number"><%= number_with_precision( fundamental.pe_low, :precision => 0, :delimiter => ",") %></td>
  <td class="number"><%= number_with_precision( fundamental.roe*100, :precision => 2, :delimiter => ",") %>%</td>
  <td class="number"><%= number_with_precision( fundamental.roa*100, :precision => 2, :delimiter => ",") %>%</td>
  <td class="number"><%= number_with_precision( fundamental.mkt_cap, :precision => 0, :delimiter => ",") %></td>
  <td class="number"><%= number_with_precision( fundamental.shrs_out, :precision => 0, :delimiter => ",") %></td>
<td><%= link_to 'Edit', edit_stock_fundamental_path(@stock, fundamental) %></td>
<td><%= link_to 'Delete', stock_fundamental_path(@stock, fundamental), :confirm => 'Are you sure?', :method => :delete %></td>
</tr>
<% end %>
<%= form_for([@stock, @stock.fundamentals.new]) do |f| %>
<tr>
  <td><%= f.date_select :date, :default => Date.today, :start_year => 1980 %></td>
  <td><%= f.text_field :eps, :size => 4 %></td>
  <td><%= f.text_field :div, :size => 4 %></td>
  <td><%= f.text_field :pe, :size => 4 %></td>
  <td><%= f.text_field :pe_high, :size => 4 %></td>
  <td><%= f.text_field :pe_low, :size => 4 %></td>
  <td><%= f.text_field :roe, :size => 4 %></td>
  <td><%= f.text_field :roa, :size => 4 %></td>
  <td><%= f.text_field :mkt_cap, :size => 4 %></td>
  <td><%= f.text_field :shrs_out, :size => 4 %></td>
</tr>
</table>
<%= f.submit %>
<% end %>

<%= form_for([@stock, @stock.researches.new]) do |f| %>
<table>
<tr><td>
<table>
<tr><td><%= f.date_select :date, :default => Date.today %></td><td/></tr>
<tr><td><%= f.date_select :eps_yr2_date, :default => @stock.researches[0][:eps_yr2_date] %></td>
<td><%= f.text_field :eps_yr2, :value => @stock.researches[0][:eps_yr2] %></td></tr>
<tr><td><%= f.date_select :eps_yr1_date, :default => @stock.researches[0][:eps_yr1_date] %></td>
<td><%= f.text_field :eps_yr1, :value => @stock.researches[0][:eps_yr1] %></td</tr>
</table>
</td><td>
    <%= f.text_area :comment, :cols => "80", :rows => "10" %>
</td></tr>
</table>
<%= f.submit %>
<% end %>

<%= render :partial => @stock.researches %>